title: Anqi Xu – 徐安琪
logo: "/content/logo.png?raw=true"
description: >
  Research Scientist &mdash Element AI
  <br>
  <br>
  <a href="https://github.com/anqixu/"><img src="content/github_icon.png?raw=true" width=32/> my codebases</a>
  <br>
  <a href="https://scholar.google.ca/citations?user=l7X99s0AAAAJ"><img src="content/google_scholar_icon.png?raw=true" width=32/> my publications</a>
  <br>
  <a href="https://www.linkedin.com/in/iamanqixu/"><img src="content/github_icon.png?raw=true" width=32/> my network</a>
  <br>
  <a href="content/cv.pdf?raw=true"><img src="content/resume_icon.png?raw=true" width=32/> my curriculum vitae</a>
  <br><hr>
  <big><a href="thesis">Thesis</a></big>
  <br>
  <big><a href="research">Research</a></big>
  
theme: jekyll-theme-minimal
google_analytics: UA-162847227-1
